#pragma config(Sensor, in1,    light_sensor,   sensorReflection)
#pragma config(Sensor, dgtl1,  leftEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  rightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl11, robot_stop,     sensorTouch)
#pragma config(Sensor, dgtl7, sonar_sensor,   sensorSONAR_cm)
#pragma config(Motor,  port1,           rightMotor,    tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port10,          leftMotor,     tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define BASELIGHT 271
#define BASEDEG 2.7
int turnArray[2] = {1, -1};
task stop_all(){
	while(!robot_stop || vexRT[Btn5D]!=1){
	}
	stopAllTasks();
}
void turn(float deg, int leftOrRight){
	while(abs(SensorValue[rightEncoder]) < deg*BASEDEG){
		motor[leftMotor] = 80* leftOrRight;
		motor[rightMotor] = -80* leftOrRight;
	}
}
void avoid(){
	motor[rightMotor] = 80;
	motor[leftMotor] = -80;
	wait1Msec(2000);
}

task main()
{
	startTask(stop_all);
	while(true){
		while(SensorValue(light_sensor) < BASELIGHT)
	{
		motor[rightMotor] = 80;
		motor[leftMotor]  = 80;
/*		if(SensorValue[rightEncoder] == SensorValue[leftEncoder])
			{
				// Move Forward
			motor[rightMotor] = 80;		// Right Motor is run at power level 80
			motor[leftMotor] = 80;		// Left Motor is run at power level 80
		}
		else if(SensorValue[rightEncoder] > SensorValue[leftEncoder])
		{
			motor[rightMotor] = 60;
			motor[leftMotor] = 80;
		}
		else
		{
			motor[rightMotor] = 80;
			motor[leftMotor] = 60;
		}*/
		while(SensorValue(sonar_sensor) < 50 ){
			avoid();
			//turn(90, turnArray[0]);
		}
	}


}}
