#pragma config(Sensor, in1,    light_sensor,   sensorReflection)
#pragma config(Sensor, dgtl1,  leftEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  rightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl7,  sonar_sensor,   sensorSONAR_cm)
#pragma config(Sensor, dgtl11, robot_stop,     sensorTouch)
#pragma config(Motor,  port1,           rightMotor,    tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port10,          leftMotor,     tmotorServoContinuousRotation, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define BASELIGHT 200
#define BASEDEG 2.7

task stop_all(){
	while(!robot_stop || vexRT[Btn5D]!=1){
	}
	stopAllTasks();
}
void stopMotors(){
	motor[rightMotor] = 0;
	motor[leftMotor] = 0;
}

void resetEncoder(){
	SensorValue[rightEncoder]=0;
	SensorValue[leftEncoder]=0;
}

void turn(float deg){
	resetEncoder();
	while(abs(SensorValue[rightEncoder]) < deg*BASEDEG){
		motor[leftMotor] = 80;
		motor[rightMotor] = -80;
	}
}
	task main()
	{
		startTask(stop_all);
		while(true){
			while(SensorValue(light_sensor) < BASELIGHT){
				while(SensorValue(sonar_sensor) < 50 || SensorValue(sonar_sensor) == -1){
					if(SensorValue[rightEncoder] == SensorValue[leftEncoder])
					{
						// Move Forward
						motor[rightMotor] = 80;		// Right Motor is run at power level 80
						motor[leftMotor] = 80;		// Left Motor is run at power level 80
					}
					else if(SensorValue[rightEncoder] > SensorValue[leftEncoder])
					{
						motor[rightMotor] = 60;
						motor[leftMotor] = 80;
					}
					else
					{
						motor[rightMotor] = 80;
						motor[leftMotor] = 60;
					}
				}
				stopMotors();
				resetEncoder();
				turn(90);
				stopMotors();

			}
		}

	}
